DATA:
  ROOT: ../data/dataset_v2
  TRAIN_FILE: ../data/dangers_5_v2/dangers_5_train.txt
  VAL_FILE: ../data/dangers_5_v2/dangers_5_val.txt
  DATASET: 'movyon'
  INPUT_SIZE: 224
  NUM_FRAMES: 32
  LABEL_LIST: labels/dangers_5.csv

MODEL:
  ARCH: 'ViT-B/16'
  DROP_PATH_RATE: 0.0
  PRETRAINED: None
  RESUME: null
  FIX_TEXT: true

TRAIN:
  EPOCHS: 10
  WARMUP_EPOCHS: 2
  LR: 1e-7
  DROPOUT_RATE: 0.5
  WEIGHT_DECAY: 0.08
  AMSGRAD: true
  CLIP_GRAD: 0.5
  BATCH_SIZE: 16
  ACCUMULATION_STEPS: 5
  BEST_METRIC: f1


OUTPUT: '.runs'
SAVE_FREQ: 25
SEED: 42
