DATA:
  ROOT: ../data/dataset
  TRAIN_FILE: ../data/dangers_5/dangers_5_train.txt
  VAL_FILE: ../data/dangers_5/dangers_5_val.txt
  DATASET: 'movyon'
  INPUT_SIZE: 224
  NUM_FRAMES: 32
  LABEL_LIST: ../data/dangers_5/class_names.csv

MODEL:
  ARCH: 'ViT-B/16'
  DROP_PATH_RATE: 0.0
  PRETRAINED: None
  RESUME: null
  FIX_TEXT: true

TRAIN:
  EPOCHS: 100
  WARMUP_EPOCHS: 10
  # WEIGHT_DECAY: 0.05
  LR: 5e-5
  BATCH_SIZE: 8
  ACCUMULATION_STEPS: 2
  BEST_METRIC: f1

TRAINER:
  ViFi_CLIP:
    USE: custom_freeze

OUTPUT: '.runs'
SAVE_FREQ: 1
PRINT_FREQ: 50
SEED: 42
